name: Bundle Stats

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Get Node.js version from package.json
        id: node-version
        run: |
          NODE_VERSION=$(node -p "require('./package.json').engines.node.replace('>=', '')")
          echo "version=$NODE_VERSION" >> $GITHUB_OUTPUT

      - name: Compare bundle stats
        uses: grafana/plugin-actions/bundle-size@ecd09d3a463b23927e5f6cb73c131e3f114ca451 # main
        with:
          node-version: ${{ steps.node-version.outputs.version }}
