name: 'PR title validation (Conventional Commits spec)'

on:
  # Using pull_request_target to allow labeling fork PRs.
  # This is safe because this workflow only reads PR metadata (title) and never checks out or runs fork code.
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

permissions:
  issues: write
  pull-requests: write

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/pr-conventional-commits@639145d78959c53c43112365837e3abd21ed67c1 # 1.5.2
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert","build","I18n"]'
          add_label: 'true'
          custom_labels: '{"docs": "type/docs", "I18n": "i18n"}'
